# @package _global_
# 12 x H100 GPUs

# When the (dataset, experiment) pair aligns with the file name of this yaml, 
# the values here will override individual yamls files for dataset, algorithm and experiment.
# useful for dataset-specific overrides


algorithm:
  pretrained_path: /scratch/s224075134/temporal_diffusion/FAR/pretrained/dcae/DCAE_BAIR_Res64-1a8547fb.pth

experiment:
  batch_size: 15
