# @package _global_

# When the (dataset, experiment) pair aligns with the file name of this yaml, 
# the values here will override individual yamls files for dataset, algorithm and experiment.
# useful for dataset-specific overrides

dataset:
  resolution: 256
  latent:
    suffix: artitok_taichi500k # 1cd9pgpb

algorithm:
  pretrained_path: /scratch/s224075134/temporal_diffusion/AR-Diffusion/vae_checkpoints/taichi_vae/ckpt_dir/checkpoint-500000/model.safetensors

experiment:
  batch_size: 1

