# @package _global_
# 12 x H100 GPUs

# When the (dataset, experiment) pair aligns with the file name of this yaml, 
# the values here will override individual yamls files for dataset, algorithm and experiment.
# useful for dataset-specific overrides

dataset:
  resolution: 256
  latent:
    suffix: kl_autoencoder_a1d993488 # 9da18dcf_temp
    # suffix: kl_autoencoder_a1d993488_temp

algorithm:
  pretrained_path: /scratch/s224075134/temporal_diffusion/FAR/pretrained/dcae/DCAE_UCF101_Res64-9da18dcf.pth

experiment:
  batch_size: 8
