# @package _global_
# 12 x H100 GPUs

# When the (dataset, experiment) pair aligns with the file name of this yaml, 
# the values here will override individual yamls files for dataset, algorithm and experiment.
# useful for dataset-specific overrides

defaults:
  - ../algorithm/backbone@algorithm.backbone: dit3d

dataset:
  num_eval_videos: 6144
  subdataset_size: 30000
  latent:
    enable: False

algorithm:
  lr_scheduler:
    num_warmup_steps: 10000
  weight_decay: 0
  backbone:
    patch_size: 2
  diffusion:
    loss_weighting:
      cum_snr_decay: 0.96
  logging:
    n_metrics_frames: 16
    max_num_videos: 128
    metrics: [vbench, fvd, is, fid, lpips, mse, ssim, psnr]
  contrastive_clip_frames: 8
  diffusion_clip_frames: 16
  contrastive_loss_weight: 0.3
  # vae:
  #   # pretrained_path: pretrained:VideoVAE_K600.ckpt
  #   batch_size: 16

experiment:
  ema:
    enable: True
    decay: 0.999
  training:
    max_steps: -1
    max_epochs: 32
    lr: 1e-4
    batch_size: 16
    checkpointing:
      every_n_train_steps: null
      every_n_epochs: 2
    data:
      num_workers: 11
      shuffle: False
  validation:
    batch_size: 16
    val_every_n_epoch: 1
    val_every_n_step: 1.0
    data:
      num_workers: 1
    limit_batch: 1.0
  test:
    batch_size: 16
    data:
      num_workers: 1
    limit_batch: 1.0
  reload_dataloaders_every_n_epochs: 1