dataset:
  num_eval_videos: 4096
  subdataset_size: 2560000

algorithm:
  backbone:
    patch_size: 1
    depth: 18
    hidden_size: 896
    num_heads: 14
  chunk_size: -1
  scheduling_matrix: full_sequence
  
experiment:
  ema:
    enable: True
    decay: 0.9999
  training:
    lr: 5e-5
  reload_dataloaders_every_n_epochs: 1